(define (problem castle-maker-problem)
    (:domain castle-maker)
    (:objects
        yellowcube1 yellowcube2 yellowcube3 yellowcube4 redcube1 redcube2 redcube3 redcube4 bluecube1 bluecube2 bluecube3 bluecube4 parallelepiped1 parallelepiped2 parallelepiped3 parallelepiped4 - object
        position1 position2 position3 position4 position5 position6 position7 position8 position9 position10 position11 position12 position13 position14 position15 position16 destination1 destination2 destination3 destination4 destination5 destination6 destination7 destination8 - location
        gripper - robot
    )
    (:init
        (ontable yellowcube1)
        (ontable yellowcube2)
        (ontable yellowcube3)
        (ontable yellowcube4)
        (ontable redcube1)
        (ontable redcube2)
        (ontable redcube3)
        (ontable redcube4)
        (ontable bluecube1)
        (ontable bluecube2)
        (ontable bluecube3)
        (ontable bluecube4)
        (ontable parallelepiped1)
        (ontable parallelepiped2)
        (ontable parallelepiped3)
        (ontable parallelepiped4)
        (clear yellowcube1)
        (clear yellowcube2)
        (clear yellowcube3)
        (clear yellowcube4)
        (clear redcube1)
        (clear redcube2)
        (clear redcube3)
        (clear redcube4)
        (clear bluecube1)
        (clear bluecube2)
        (clear bluecube3)
        (clear bluecube4)
        (clear parallelepiped1)
        (clear parallelepiped2)
        (clear parallelepiped3)
        (clear parallelepiped4)
        (at yellowcube1 position1)
        (at yellowcube2 position2)
        (at yellowcube3 position3)
        (at yellowcube4 position4)
        (at redcube1 position5)
        (at redcube2 position6)
        (at redcube3 position7)
        (at redcube4 position8)
        (at bluecube1 position9)
        (at bluecube2 position10)
        (at bluecube3 position11)
        (at bluecube4 position12)
        (at parallelepiped1 position13)
        (at parallelepiped2 position14)
        (at parallelepiped3 position15)
        (at parallelepiped4 position16)
        (notbusy gripper)
        (emptyhand gripper)
        )
    (:goal
        (and (on yellowcube2 yellowcube1) (at yellowcube1 destination1) (on bluecube2 bluecube1) (at bluecube1 destination2)(on yellowcube4 yellowcube3) (at yellowcube3 destination3)(on redcube2 redcube1) (at redcube1 destination4)(ontable parallelepiped1) (at parallelepiped1 destination5)(ontable parallelepiped2) (at parallelepiped2 destination6)(ontable parallelepiped3) (at parallelepiped3 destination7)(ontable parallelepiped4) (at parallelepiped4 destination8))
    )
)